// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfhNtmhmmmbvDI8o0ujmmpB27D2qzFNrc',
    appId: '1:358914495034:web:1ead750e9366b7e9969b03',
    messagingSenderId: '358914495034',
    projectId: 'reserve-sample-cdc20',
    authDomain: 'reserve-sample-cdc20.firebaseapp.com',
    storageBucket: 'reserve-sample-cdc20.appspot.com',
    measurementId: 'G-SYW17T4KFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvUOJQFoIPe3D4JddlAU7uYVCTauDxVhw',
    appId: '1:358914495034:android:cbd6ce75e37c15e9969b03',
    messagingSenderId: '358914495034',
    projectId: 'reserve-sample-cdc20',
    storageBucket: 'reserve-sample-cdc20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuIaLD2u_l5piQ-96ZPGnAF5YcjJpa6uw',
    appId: '1:358914495034:ios:ac6135fa2adc6be1969b03',
    messagingSenderId: '358914495034',
    projectId: 'reserve-sample-cdc20',
    storageBucket: 'reserve-sample-cdc20.appspot.com',
    iosClientId: '358914495034-rfqce1lm9u8i57ud4mjb1qse0r2vpdj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.sample01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuIaLD2u_l5piQ-96ZPGnAF5YcjJpa6uw',
    appId: '1:358914495034:ios:ac6135fa2adc6be1969b03',
    messagingSenderId: '358914495034',
    projectId: 'reserve-sample-cdc20',
    storageBucket: 'reserve-sample-cdc20.appspot.com',
    iosClientId: '358914495034-rfqce1lm9u8i57ud4mjb1qse0r2vpdj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.sample01',
  );
}
